language: c++

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - Build=linux64
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - cmake --build . -j $(nproc)
      addons:
        apt:
          packages:
            - cmake
            - libsdl2-dev
            - libsdl2-image-dev
            - libuv1-dev
            - libjack-jackd2-dev
            - libpulse-dev
            - libasound2-dev
            - libfluidsynth-dev
